[git_branch]
disabled = true
[git_status]
disabled = true
[git_commit]
disabled = true


[python]
disabled = true
[rust]
disabled = true
[package]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true
